### ISSUE TITLE
Procedures: Making a pull request

### ISSUE THREAD

**Issue by xinnanyemm** [MetaMask/contributor-docs#19]
This document would cover:
- Writing a good pull request description by providing context (not just a link to an issue), a description of before and after, screenshots or screencaps for UI features, and instructions for reviewers to manually test your changes if necessary
- Explaining specific changes in the code by writing a self-review and leaving comments for other reviewers

**Comment by MajorLift** [comment]
Closed by https://github.com/MetaMask/contributor-docs/pull/45
