### ISSUE TITLE
Procedures: Reviewing a pull request

### ISSUE THREAD

**Issue by xinnanyemm** [MetaMask/contributor-docs#20]
This document would include guidelines such as:
- What to look for when reviewing code
- Manually testing the changes in the PR
- Leaving constructive feedback (asking questions, assuming good intent, etc.)
- Leaving actionable feedback (providing suggestions, etc.)

**Comment by MajorLift** [comment]
Closed by https://github.com/MetaMask/contributor-docs/pull/45
