### ISSUE TITLE
Standards: Unit testing

### ISSUE THREAD

**Issue by xinnanyemm** [MetaMask/contributor-docs#25]
This document would cover best practices and guidelines on writing tests that are complete and maintainable. Sections could include:
- The importance of naming tests well
- Organizing tests
- The four-phase test pattern
- Why reducing duplication in tests is an anti-goal
- Writing isolated tests (and why Jest hooks are counterproductive)

**Comment by Gudahtt** [comment]
We recently discussed test naming conventions as a team, and have agreed that we should not prefix test descriptions with "should". We will use BDD-style descriptions, but they will assert what the code-under-test is doing rather than saying what it should do.

**Comment by mcmire** [comment]
Note that this ticket is essentially a subset of https://github.com/MetaMask/contributor-docs/issues/5. For now we'll focus on unit testing and we can incorporate into a complete guide on testing later.

**Comment by mcmire** [comment]
For context in estimation, I plan on adding more guidelines similar to those I've added for JavaScript and TypeScript. In other words, they will be essentially bullet points that act as guideposts for writing better tests, with a blurb for each point and some examples. I don't plan on writing anything that's long-form, despite what the description might indicate.
