### ISSUE TITLE
Document our philosophy on Testing

### ISSUE THREAD

**Issue by brad-decker** [MetaMask/contributor-docs#5]
Suggested sections:
1. Unit vs Integration vs E2E
2. How should we approach unit testing?
3. Mocking/Spying
4. Snapshot philosophy
5. Tooling (jest, etc)

Essentially give as much background into our current thinking around tests so that a new engineer is effective at reading existing tests as well as writing new ones.

**Comment by Gudahtt** [comment]
Documentation was added for 1. in #99.

We have covered 2 and 5 adequately well in earlier changes as well.

There are still some additions that I'd like to make about 3 and 4. I have captured the remaining work on these topics in #114 and #115
