### ISSUE TITLE
Shared Libraries - 2023/Q4/O2/KR2 - Increase awareness and NPS Score around the contributor documentation from NPS 22 to NPS 35

### ISSUE THREAD

**Issue by mcmire** [MetaMask/contributor-docs#50]
The more people contribute to the documentation — either author documents themselves or contribute to discussions — the more that the repository represents the opinions of the whole organization and not just any one team.

The Shared Libraries team will set an example by starting to refer to the docs in pull requests ourselves and also encouraging other teams (such as the extension or mobile teams) to share any code guidelines they might be keeping privately.

**Comment by desi** [comment]
Closing this epic as all items are included in a different epics that crosses quarters. This is being done as part of a reorg for the MM Roadmap
